const express = require('express');
const cartRouter = express.Router();
const {authentication} = require('../middlewares/authenticationToken');
const{createCart,deleteCart,updateCart,getCart,deleteAllCart,updateIsCheck} = require('../models/cart');
cartRouter.post("/createCart",authentication,createCart);
cartRouter.get("/getCart/:buyerId",authentication,getCart);
cartRouter.delete("/deleteCart/:cartId/:productId/:quantity",authentication,deleteCart);
cartRouter.delete("/deleteAllCart/:buyerId",authentication,deleteAllCart);
cartRouter.put("/updateCart",authentication,updateCart);
cartRouter.put("/updateIsCheck",authentication,updateIsCheck);
module.exports = cartRouter;
